# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=100, unique=True)),
                ('activate', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('superintendent', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('indicator_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_indeicator', models.BooleanField(default=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictIndicatorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_x', models.CharField(blank=True, max_length=100)),
                ('dimension_y', models.CharField(blank=True, max_length=100)),
                ('key_value', models.CharField(db_index=True, max_length=100)),
                ('data_type', models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictIndicatorDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='District_Indicator_Data')),
                ('import_file', models.BooleanField(default=False)),
                ('district_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictIndicator')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictIndicatorSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.District')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictNumberOfStudentAndTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=False)),
                ('student', models.IntegerField(null=True)),
                ('teacher', models.IntegerField(null=True)),
                ('school', models.IntegerField(null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.District')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(max_length=100, unique=True)),
                ('school_name', models.CharField(max_length=100)),
                ('school_type', models.CharField(max_length=100)),
                ('grade_type', models.CharField(max_length=100)),
                ('principal', models.CharField(blank=True, max_length=100)),
                ('activate', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('elementary_school', models.BooleanField(default=False)),
                ('middle_school', models.BooleanField(default=False)),
                ('high_school', models.BooleanField(default=False)),
                ('grade_pk', models.BooleanField(default=False)),
                ('grade_k', models.BooleanField(default=False)),
                ('grade_1', models.BooleanField(default=False)),
                ('grade_2', models.BooleanField(default=False)),
                ('grade_3', models.BooleanField(default=False)),
                ('grade_4', models.BooleanField(default=False)),
                ('grade_5', models.BooleanField(default=False)),
                ('grade_6', models.BooleanField(default=False)),
                ('grade_7', models.BooleanField(default=False)),
                ('grade_8', models.BooleanField(default=False)),
                ('grade_9', models.BooleanField(default=False)),
                ('grade_10', models.BooleanField(default=False)),
                ('grade_11', models.BooleanField(default=False)),
                ('grade_12', models.BooleanField(default=False)),
                ('indicator_modified', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.District')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_indeicator', models.BooleanField(default=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolIndicatorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_x', models.CharField(blank=True, max_length=100)),
                ('dimension_y', models.CharField(blank=True, max_length=100)),
                ('key_value', models.CharField(db_index=True, max_length=100)),
                ('data_type', models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolIndicatorDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='School_Indicator_Data')),
                ('import_file', models.BooleanField(default=False)),
                ('school_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolIndicator')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolIndicatorSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.School')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolNumberOfStudentAndTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=False)),
                ('student', models.IntegerField(null=True)),
                ('teacher', models.IntegerField(null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.School')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='schoolnumberofstudentandteacher',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SchoolYear'),
        ),
        migrations.AddField(
            model_name='schoolindicatordataset',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SchoolYear'),
        ),
        migrations.AddField(
            model_name='schoolindicatordata',
            name='school_indicator_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolIndicatorDataSet'),
        ),
        migrations.AddField(
            model_name='schoolindicator',
            name='school_indicator_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolIndicatorSet'),
        ),
        migrations.AddField(
            model_name='schoolindicator',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.IndicatorTitle'),
        ),
        migrations.AddField(
            model_name='districtnumberofstudentandteacher',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SchoolYear'),
        ),
        migrations.AddField(
            model_name='districtindicatordataset',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SchoolYear'),
        ),
        migrations.AddField(
            model_name='districtindicatordata',
            name='district_indicator_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictIndicatorDataSet'),
        ),
        migrations.AddField(
            model_name='districtindicator',
            name='district_indicator_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictIndicatorSet'),
        ),
        migrations.AddField(
            model_name='districtindicator',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.IndicatorTitle'),
        ),
    ]
