# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160222_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtindicator',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolindicator',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
