# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0002_auto_20160226_1407'),
        ('data', '0003_auto_20160222_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictDisplayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionFor')),
                ('district_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictIndicator')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDisplayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionFor')),
                ('school_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolIndicator')),
            ],
        ),
    ]
