# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160226_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtnumberofstudentandteacher',
            name='district',
        ),
        migrations.RemoveField(
            model_name='districtnumberofstudentandteacher',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='schoolnumberofstudentandteacher',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schoolnumberofstudentandteacher',
            name='school_year',
        ),
        migrations.AddField(
            model_name='district',
            name='number_of_student',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='number_of_teacher',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='number_of_student',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='number_of_teacher',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DistrictNumberOfStudentAndTeacher',
        ),
        migrations.DeleteModel(
            name='SchoolNumberOfStudentAndTeacher',
        ),
    ]
