# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0003_auto_20160301_1402'),
        ('data', '0006_auto_20160229_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=100, unique=True)),
                ('activate', models.BooleanField(default=True)),
                ('number_of_student', models.IntegerField(blank=True, null=True)),
                ('number_of_teacher', models.IntegerField(blank=True, null=True)),
                ('number_of_school', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('commissioner', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('indicator_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateDisplayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionFor')),
            ],
        ),
        migrations.CreateModel(
            name='StateIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('short_title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_indeicator', models.BooleanField(default=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateIndicatorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_x', models.CharField(blank=True, max_length=100)),
                ('dimension_y', models.CharField(blank=True, max_length=100)),
                ('key_value', models.CharField(db_index=True, max_length=100)),
                ('data_type', models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string')], max_length=7)),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.IndicatorFile')),
            ],
        ),
        migrations.CreateModel(
            name='StateIndicatorDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='State_Indicator_Data')),
                ('import_file', models.BooleanField(default=False)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SchoolYear')),
                ('state_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateIndicator')),
            ],
        ),
        migrations.CreateModel(
            name='StateIndicatorSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.State')),
            ],
        ),
        migrations.AddField(
            model_name='stateindicatordata',
            name='state_indicator_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateIndicatorDataSet'),
        ),
        migrations.AddField(
            model_name='stateindicator',
            name='state_indicator_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateIndicatorSet'),
        ),
        migrations.AddField(
            model_name='stateindicator',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.IndicatorTitle'),
        ),
        migrations.AddField(
            model_name='statedisplaydata',
            name='state_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateIndicator'),
        ),
    ]
