# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20160301_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='default_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
