# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_district_us_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
