# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20160302_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictDisplayDataY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('district_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictIndicator')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDisplayDataY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('school_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolIndicator')),
            ],
        ),
        migrations.CreateModel(
            name='StateDisplayDataY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('state_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateIndicator')),
            ],
        ),
    ]
