# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_districtdisplaydatay_schooldisplaydatay_statedisplaydatay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtdisplaydatay',
            name='display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName'),
        ),
        migrations.AlterField(
            model_name='schooldisplaydatay',
            name='display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName'),
        ),
        migrations.AlterField(
            model_name='statedisplaydatay',
            name='display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName'),
        ),
    ]
