# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 14:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20160303_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
