# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 16:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20160304_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtindicator',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schoolindicator',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stateindicator',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
