# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20160304_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string')], default='STRING', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string')], default='STRING', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stateindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string')], default='STRING', max_length=7),
            preserve_default=False,
        ),
    ]
