# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20160307_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtindicator',
            old_name='data_indeicator',
            new_name='data_indicator',
        ),
        migrations.RenameField(
            model_name='schoolindicator',
            old_name='data_indeicator',
            new_name='data_indicator',
        ),
        migrations.RenameField(
            model_name='stateindicator',
            old_name='data_indeicator',
            new_name='data_indicator',
        ),
    ]
