# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0005_auto_20160302_1611'),
        ('data', '0016_auto_20160308_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailDataSetTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictIndicatorDetailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_x', models.CharField(blank=True, max_length=100)),
                ('dimension_y', models.CharField(blank=True, max_length=100)),
                ('key_value', models.CharField(db_index=True, max_length=100)),
                ('data_type', models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictIndicatorDetailDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(choices=[('BAR_CHART', 'Bar Chart'), ('PIE_CHART', 'Pie Chart'), ('SHOW_TABLE', 'Show Table')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolIndicatorDetailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_x', models.CharField(blank=True, max_length=100)),
                ('dimension_y', models.CharField(blank=True, max_length=100)),
                ('key_value', models.CharField(db_index=True, max_length=100)),
                ('data_type', models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7)),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.IndicatorFile')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolIndicatorDetailDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(choices=[('BAR_CHART', 'Bar Chart'), ('PIE_CHART', 'Pie Chart'), ('SHOW_TABLE', 'Show Table')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='StateIndicatorDetailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_x', models.CharField(blank=True, max_length=100)),
                ('dimension_y', models.CharField(blank=True, max_length=100)),
                ('key_value', models.CharField(db_index=True, max_length=100)),
                ('data_type', models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7)),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.IndicatorFile')),
            ],
        ),
        migrations.CreateModel(
            name='StateIndicatorDetailDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(choices=[('BAR_CHART', 'Bar Chart'), ('PIE_CHART', 'Pie Chart'), ('SHOW_TABLE', 'Show Table')], max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='districtindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7),
        ),
        migrations.AlterField(
            model_name='districtindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7),
        ),
        migrations.AlterField(
            model_name='stateindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7),
        ),
        migrations.AlterField(
            model_name='stateindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7),
        ),
        migrations.AddField(
            model_name='stateindicatordetaildataset',
            name='indicator_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.StateIndicatorData'),
        ),
        migrations.AddField(
            model_name='stateindicatordetaildataset',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DetailDataSetTitle'),
        ),
        migrations.AddField(
            model_name='stateindicatordetaildata',
            name='state_indicator_detail_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateIndicatorDetailDataSet'),
        ),
        migrations.AddField(
            model_name='schoolindicatordetaildataset',
            name='indicator_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SchoolIndicatorData'),
        ),
        migrations.AddField(
            model_name='schoolindicatordetaildataset',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DetailDataSetTitle'),
        ),
        migrations.AddField(
            model_name='schoolindicatordetaildata',
            name='school_indicator_detail_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolIndicatorDetailDataSet'),
        ),
        migrations.AddField(
            model_name='districtindicatordetaildataset',
            name='indicator_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DistrictIndicatorData'),
        ),
        migrations.AddField(
            model_name='districtindicatordetaildataset',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DetailDataSetTitle'),
        ),
        migrations.AddField(
            model_name='districtindicatordetaildata',
            name='district_indicator_detail_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictIndicatorDetailDataSet'),
        ),
        migrations.AddField(
            model_name='districtindicatordetaildata',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.IndicatorFile'),
        ),
    ]
