# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20160308_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string')], max_length=7),
        ),
        migrations.AlterField(
            model_name='districtindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string')], max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string')], max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string')], max_length=7),
        ),
        migrations.AlterField(
            model_name='stateindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string')], max_length=7),
        ),
        migrations.AlterField(
            model_name='stateindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string')], max_length=7),
        ),
    ]
