# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0007_auto_20160314_1751'),
        ('data', '0017_auto_20160314_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictDisplayDataYDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictDisplayDataYDetailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_dimension_y_name', models.CharField(blank=True, max_length=100)),
                ('new_dimension_x_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictDisplayDataYDetailSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictDisplayDataYDetail')),
            ],
        ),
        migrations.AddField(
            model_name='districtdisplaydataydetaildata',
            name='detail_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DistrictDisplayDataYDetailSet'),
        ),
        migrations.AddField(
            model_name='districtdisplaydataydetaildata',
            name='dimension_x_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionFor'),
        ),
        migrations.AddField(
            model_name='districtdisplaydataydetaildata',
            name='dimension_y_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName'),
        ),
        migrations.AddField(
            model_name='districtdisplaydatay',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictDisplayDataYDetail'),
        ),
    ]
