# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20160314_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdisplaydataydetailset',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
