# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20160310_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtindicatordetaildataset',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schoolindicatordetaildataset',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stateindicatordetaildataset',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='districtindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR_CHART', 'Bar Chart'), ('PIE_CHART', 'Pie Chart'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR_CHART', 'Bar Chart'), ('PIE_CHART', 'Pie Chart'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stateindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR_CHART', 'Bar Chart'), ('PIE_CHART', 'Pie Chart'), ('TABLE', 'Table')], max_length=20),
        ),
    ]
