# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_districtdisplaydataydetail_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdisplaydataydetaildata',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
