# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20160311_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtindicatordetaildata',
            name='import_job',
        ),
    ]
