# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0008_auto_20160311_1748'),
        ('data', '0021_remove_districtindicatordetaildata_import_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtindicatordetaildata',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.IndicatorDetailFile'),
        ),
    ]
