# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0009_auto_20160311_1757'),
        ('data', '0022_districtindicatordetaildata_import_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
