# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20160316_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdisplaydataydetaildata',
            name='new_dimension_x_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.CustomDimensionXName'),
        ),
        migrations.AddField(
            model_name='districtdisplaydataydetaildata',
            name='new_dimension_y_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.CustomDimensionYName'),
        ),
    ]
