# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0007_auto_20160314_1751'),
        ('data', '0023_auto_20160316_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDisplayDataYDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDisplayDataYDetailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDisplayDataYDetailSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolDisplayDataYDetail')),
            ],
        ),
        migrations.AlterField(
            model_name='districtindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string')], default='STRING', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string')], default='STRING', max_length=7),
        ),
        migrations.AlterField(
            model_name='stateindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string')], default='STRING', max_length=7),
        ),
        migrations.AddField(
            model_name='schooldisplaydataydetaildata',
            name='detail_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SchoolDisplayDataYDetailSet'),
        ),
        migrations.AddField(
            model_name='schooldisplaydataydetaildata',
            name='dimension_x_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionFor'),
        ),
        migrations.AddField(
            model_name='schooldisplaydataydetaildata',
            name='dimension_y_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName'),
        ),
        migrations.AddField(
            model_name='schooldisplaydataydetaildata',
            name='new_dimension_x_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.CustomDimensionXName'),
        ),
        migrations.AddField(
            model_name='schooldisplaydataydetaildata',
            name='new_dimension_y_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.CustomDimensionYName'),
        ),
    ]
