# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20160316_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldisplaydatay',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolDisplayDataYDetail'),
        ),
    ]
