# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0007_auto_20160314_1751'),
        ('data', '0025_schooldisplaydatay_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateDisplayDataYDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateDisplayDataYDetailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StateDisplayDataYDetailSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateDisplayDataYDetail')),
            ],
        ),
        migrations.AlterField(
            model_name='districtdisplaydataydetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='schooldisplaydataydetail',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='statedisplaydataydetaildata',
            name='detail_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.StateDisplayDataYDetailSet'),
        ),
        migrations.AddField(
            model_name='statedisplaydataydetaildata',
            name='dimension_x_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionFor'),
        ),
        migrations.AddField(
            model_name='statedisplaydataydetaildata',
            name='dimension_y_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName'),
        ),
        migrations.AddField(
            model_name='statedisplaydataydetaildata',
            name='new_dimension_x_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.CustomDimensionXName'),
        ),
        migrations.AddField(
            model_name='statedisplaydataydetaildata',
            name='new_dimension_y_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.CustomDimensionYName'),
        ),
        migrations.AddField(
            model_name='statedisplaydatay',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateDisplayDataYDetail'),
        ),
    ]
