# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdisplaydata',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='districtdisplaydatay',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schooldisplaydata',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schooldisplaydatay',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='statedisplaydata',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='statedisplaydatay',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='districtindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='districtindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], default='STRING', max_length=7),
        ),
        migrations.AlterField(
            model_name='districtindicatordetaildata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7),
        ),
        migrations.AlterField(
            model_name='districtindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart'), ('AREA-CHART', 'Area Chart'), ('PIE-CHART', 'Pie Chart'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], default='STRING', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolindicatordetaildata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart'), ('AREA-CHART', 'Area Chart'), ('PIE-CHART', 'Pie Chart'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stateindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7),
        ),
        migrations.AlterField(
            model_name='stateindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], default='STRING', max_length=7),
        ),
        migrations.AlterField(
            model_name='stateindicatordetaildata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('STRING', 'string'), ('SUBDATASET', 'subdataset')], max_length=7),
        ),
        migrations.AlterField(
            model_name='stateindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart'), ('AREA-CHART', 'Area Chart'), ('PIE-CHART', 'Pie Chart'), ('TABLE', 'Table')], max_length=20),
        ),
    ]
