# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20160321_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdisplaydataydetailset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart'), ('AREA-CHART', 'Area Chart'), ('PIE-CHART', 'Pie Chart'), ('TABLE', 'Table')], default='TABLE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schooldisplaydataydetailset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart'), ('AREA-CHART', 'Area Chart'), ('PIE-CHART', 'Pie Chart'), ('TABLE', 'Table')], default='TABLE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statedisplaydataydetailset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart'), ('AREA-CHART', 'Area Chart'), ('PIE-CHART', 'Pie Chart'), ('TABLE', 'Table')], default='TABLE', max_length=20),
            preserve_default=False,
        ),
    ]
