# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20160322_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='statedisplaydataydetail',
            name='state_display_type',
            field=models.CharField(choices=[('DETAILE', 'Show detail page'), ('DISTRICT', 'Show district page'), ('SCHOOL', 'Show school page')], default='SCHOOL', max_length=20),
        ),
    ]
