# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_statedisplaydataydetail_state_display_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtindicatordata',
            name='dimension_x',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='districtindicatordata',
            name='dimension_y',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='districtindicatordetaildata',
            name='dimension_x',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='districtindicatordetaildata',
            name='dimension_y',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolindicatordata',
            name='dimension_x',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolindicatordata',
            name='dimension_y',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolindicatordetaildata',
            name='dimension_x',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolindicatordetaildata',
            name='dimension_y',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stateindicatordata',
            name='dimension_x',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stateindicatordata',
            name='dimension_y',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stateindicatordetaildata',
            name='dimension_x',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stateindicatordetaildata',
            name='dimension_y',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
