# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20160323_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdisplaydataydetail',
            name='district_display_type',
            field=models.CharField(choices=[('DETAILE', 'Show detail page'), ('SCHOOL', 'Show school page')], default='DETAILE', max_length=20),
        ),
    ]
