# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_districtdisplaydataydetail_district_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtindicator',
            name='switch_highchart_xy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolindicator',
            name='switch_highchart_xy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stateindicator',
            name='switch_highchart_xy',
            field=models.BooleanField(default=True),
        ),
    ]
