# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0013_auto_20160323_1519'),
        ('data', '0033_auto_20160331_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictOverTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictOverTimeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(default=True)),
                ('dimension_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName')),
                ('district_over_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DistrictOverTime')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictOverTimeSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('district_over_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DistrictOverTime')),
                ('lookup_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.LookUpTable')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolOverTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolOverTimeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(default=True)),
                ('dimension_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName')),
                ('school_over_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SchoolOverTime')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolOverTimeSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('lookup_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.LookUpTable')),
                ('school_over_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SchoolOverTime')),
            ],
        ),
        migrations.CreateModel(
            name='StateOverTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StateOverTimeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField(default=True)),
                ('dimension_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName')),
                ('state_over_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.StateOverTime')),
            ],
        ),
        migrations.CreateModel(
            name='StateOverTimeSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('lookup_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.LookUpTable')),
                ('state_over_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.StateOverTime')),
            ],
        ),
        migrations.AddField(
            model_name='districtindicator',
            name='over_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictOverTime'),
        ),
        migrations.AddField(
            model_name='schoolindicator',
            name='over_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolOverTime'),
        ),
        migrations.AddField(
            model_name='stateindicator',
            name='over_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateOverTime'),
        ),
    ]
