# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_auto_20160406_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtovertimeelement',
            name='color_hex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schoolovertimeelement',
            name='color_hex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stateovertimeelement',
            name='color_hex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
