# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_auto_20160406_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdimensionyname',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
    ]
