# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_auto_20160408_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdisplaydataydetailset',
            name='y_axis_title_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schooldisplaydataydetailset',
            name='y_axis_title_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statedisplaydataydetailset',
            name='y_axis_title_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
