# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_auto_20160408_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdimensionyname',
            name='color_hex',
            field=models.CharField(blank=True, help_text='You can user http://www.color-hex.com/', max_length=100),
        ),
    ]
