# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_customdimensionyname_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdimensionyname',
            name='color_note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
