# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_customdimensionyname_color_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtdisplaydataydetailset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='districtindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schooldisplaydataydetailset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statedisplaydataydetailset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stateindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
    ]
