# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_auto_20160412_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, max_length=100)),
                ('setting_from', models.CharField(blank=True, max_length=100)),
                ('setting_to', models.CharField(blank=True, max_length=100)),
                ('label_text', models.CharField(blank=True, max_length=100)),
                ('label_color', models.CharField(blank=True, max_length=100)),
                ('y_position', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlotLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_color', models.CharField(blank=True, max_length=100)),
                ('dash_style', models.CharField(blank=True, default='longdashdot', max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('width', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlotSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='plotline',
            name='plot_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PlotSetting'),
        ),
        migrations.AddField(
            model_name='plotband',
            name='plot_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PlotSetting'),
        ),
        migrations.AddField(
            model_name='districtdisplaydataydetailset',
            name='plot_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.PlotSetting'),
        ),
        migrations.AddField(
            model_name='schooldisplaydataydetailset',
            name='plot_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.PlotSetting'),
        ),
        migrations.AddField(
            model_name='statedisplaydataydetailset',
            name='plot_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.PlotSetting'),
        ),
    ]
