# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0015_systemcode_display_name'),
        ('data', '0043_auto_20160428_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDisplayDataSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionFor')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.IndicatorTitle')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDisplayDataYSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(choices=[('ALL', 'All'), ('ELEMENTARY', 'Elementary School'), ('MIDDLE', 'Middle School'), ('HIGH', 'High School'), ('GRADE_PK', 'Grade pk'), ('GRADE_K', 'Grade k'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8'), ('GRADE_9', 'Grade 9'), ('GRADE_10', 'Grade 10'), ('GRADE_11', 'Grade 11'), ('GRADE_12', 'Grade 12')], default='SCHOOL', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictDisplayDataYDetail')),
                ('display', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.IndicatorTitle')),
            ],
        ),
        migrations.AlterField(
            model_name='districtdisplaydataydetailset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('BAR-CHART-ONLY', 'Bar Chart Only'), ('HORZ-BAR-CHART', 'Horizontal Bar Chart'), ('HORZ-BAR-CHART-ONLY', 'Horizontal Bar Chart Only'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='districtindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('BAR-CHART-ONLY', 'Bar Chart Only'), ('HORZ-BAR-CHART', 'Horizontal Bar Chart'), ('HORZ-BAR-CHART-ONLY', 'Horizontal Bar Chart Only'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schooldisplaydataydetailset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('BAR-CHART-ONLY', 'Bar Chart Only'), ('HORZ-BAR-CHART', 'Horizontal Bar Chart'), ('HORZ-BAR-CHART-ONLY', 'Horizontal Bar Chart Only'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('BAR-CHART-ONLY', 'Bar Chart Only'), ('HORZ-BAR-CHART', 'Horizontal Bar Chart'), ('HORZ-BAR-CHART-ONLY', 'Horizontal Bar Chart Only'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statedisplaydataydetailset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('BAR-CHART-ONLY', 'Bar Chart Only'), ('HORZ-BAR-CHART', 'Horizontal Bar Chart'), ('HORZ-BAR-CHART-ONLY', 'Horizontal Bar Chart Only'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stateindicatordetaildataset',
            name='display_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('BAR-CHART-ONLY', 'Bar Chart Only'), ('HORZ-BAR-CHART', 'Horizontal Bar Chart'), ('HORZ-BAR-CHART-ONLY', 'Horizontal Bar Chart Only'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], max_length=20),
        ),
    ]
