# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_auto_20160502_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldisplaydataysetting',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolDisplayDataYDetail'),
        ),
        migrations.AlterField(
            model_name='schooldisplaydataysetting',
            name='grade_level',
            field=models.CharField(choices=[('ALL', 'All'), ('ELEMENTARY', 'Elementary School'), ('MIDDLE', 'Middle School'), ('HIGH', 'High School'), ('GRADE_PK', 'Grade pk'), ('GRADE_K', 'Grade k'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8'), ('GRADE_9', 'Grade 9'), ('GRADE_10', 'Grade 10'), ('GRADE_11', 'Grade 11'), ('GRADE_12', 'Grade 12')], max_length=20),
        ),
    ]
