# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0015_systemcode_display_name'),
        ('data', '0045_auto_20160502_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictDisplayDataSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionFor')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.IndicatorTitle')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictDisplayDataYSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictDisplayDataYDetail')),
                ('display', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.IndicatorTitle')),
            ],
        ),
    ]
