# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0015_systemcode_display_name'),
        ('data', '0046_districtdisplaydatasetting_districtdisplaydataysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictSummery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictDisplayDataYDetail')),
                ('display', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName')),
            ],
        ),
        migrations.CreateModel(
            name='StateSummery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateDisplayDataYDetail')),
                ('display', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName')),
            ],
        ),
        migrations.AlterField(
            model_name='districtdisplaydataydetailset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], default='PERCENT', max_length=7),
        ),
        migrations.AlterField(
            model_name='districtindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], max_length=20),
        ),
        migrations.AlterField(
            model_name='districtindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], default='STRING', max_length=7),
        ),
        migrations.AlterField(
            model_name='districtindicatordetaildata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], max_length=7),
        ),
        migrations.AlterField(
            model_name='districtovertime',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], default='NUMERIC', max_length=7),
        ),
        migrations.AlterField(
            model_name='schooldisplaydataydetailset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], default='PERCENT', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], default='STRING', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolindicatordetaildata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolovertime',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], default='NUMERIC', max_length=7),
        ),
        migrations.AlterField(
            model_name='statedisplaydataydetailset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], default='PERCENT', max_length=7),
        ),
        migrations.AlterField(
            model_name='stateindicatordata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], max_length=7),
        ),
        migrations.AlterField(
            model_name='stateindicatordataset',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], default='STRING', max_length=7),
        ),
        migrations.AlterField(
            model_name='stateindicatordetaildata',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], max_length=7),
        ),
        migrations.AlterField(
            model_name='stateovertime',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'numeric'), ('PERCENT', 'percent'), ('RATIO', 'ratio'), ('STRING', 'string')], default='NUMERIC', max_length=7),
        ),
    ]
