# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_auto_20160504_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=', '='), ('!=', '!=')], max_length=20)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('display_value', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='indicatortitle',
            name='data_type',
            field=models.CharField(blank=True, choices=[('NUMERIC', 'Numeric'), ('NUMERIC_COMMA', 'Numeric with comma'), ('PERCENT', 'Percent'), ('RATIO', 'Ratio'), ('DOLLARS', 'Dollars'), ('DOLLARS_COMMA', 'Dollars with comma')], max_length=20),
        ),
        migrations.AddField(
            model_name='indicatortitle',
            name='rounding_decimal_place',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customvalue',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.IndicatorTitle'),
        ),
    ]
