# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_auto_20160505_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtovertime',
            name='stack_label_negative',
            field=models.CharField(blank=True, default='Total:', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='districtovertime',
            name='stack_label_positive',
            field=models.CharField(blank=True, default='Total:', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schoolovertime',
            name='stack_label_negative',
            field=models.CharField(blank=True, default='Total:', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schoolovertime',
            name='stack_label_positive',
            field=models.CharField(blank=True, default='Total:', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stateovertime',
            name='stack_label_negative',
            field=models.CharField(blank=True, default='Total:', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stateovertime',
            name='stack_label_positive',
            field=models.CharField(blank=True, default='Total:', max_length=200, null=True),
        ),
    ]
