# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_auto_20160527_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtovertime',
            name='chart_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('BAR-CHART-ONLY', 'Bar Chart Only'), ('HORZ-BAR-CHART', 'Horizontal Bar Chart'), ('HORZ-BAR-CHART-ONLY', 'Horizontal Bar Chart Only'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], default='BAR-CHART', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolovertime',
            name='chart_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('BAR-CHART-ONLY', 'Bar Chart Only'), ('HORZ-BAR-CHART', 'Horizontal Bar Chart'), ('HORZ-BAR-CHART-ONLY', 'Horizontal Bar Chart Only'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], default='BAR-CHART', max_length=50),
        ),
        migrations.AddField(
            model_name='stateovertime',
            name='chart_type',
            field=models.CharField(choices=[('BAR-CHART', 'Bar Chart'), ('BAR-CHART-ONLY', 'Bar Chart Only'), ('HORZ-BAR-CHART', 'Horizontal Bar Chart'), ('HORZ-BAR-CHART-ONLY', 'Horizontal Bar Chart Only'), ('LINE-CHART', 'Line Chart (under construction)'), ('AREA-CHART', 'Area Chart (under construction)'), ('PIE-CHART', 'Pie Chart (under construction)'), ('TABLE', 'Table')], default='BAR-CHART', max_length=50),
        ),
    ]
