# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_auto_20160822_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtovertime',
            name='over_time_type',
            field=models.CharField(choices=[('REFRESH_OVER_TIME', 'When user select new data refresh chart and table'), ('APPEND_OVER_TIME', 'When user select new data append to chart and table')], default='REFRESH_OVER_TIME', max_length=17),
        ),
        migrations.AddField(
            model_name='schoolovertime',
            name='over_time_type',
            field=models.CharField(choices=[('REFRESH_OVER_TIME', 'When user select new data refresh chart and table'), ('APPEND_OVER_TIME', 'When user select new data append to chart and table')], default='REFRESH_OVER_TIME', max_length=17),
        ),
        migrations.AddField(
            model_name='stateovertime',
            name='over_time_type',
            field=models.CharField(choices=[('REFRESH_OVER_TIME', 'When user select new data refresh chart and table'), ('APPEND_OVER_TIME', 'When user select new data append to chart and table')], default='REFRESH_OVER_TIME', max_length=17),
        ),
    ]
