# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_auto_20160823_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtsummery',
            name='sorting_plug',
            field=models.CharField(blank=True, help_text='https://datatables.net/plug-ins/sorting/', max_length=100),
        ),
        migrations.AddField(
            model_name='statesummery',
            name='sorting_plug',
            field=models.CharField(blank=True, help_text='https://datatables.net/plug-ins/sorting/', max_length=100),
        ),
        migrations.AlterField(
            model_name='districtovertime',
            name='over_time_type',
            field=models.CharField(choices=[('REFRESH_OVER_TIME', 'Refresh chart and table, when user select new data.'), ('APPEND_OVER_TIME', 'Append to chart and table, when user select new data.')], default='REFRESH_OVER_TIME', max_length=17),
        ),
        migrations.AlterField(
            model_name='schoolovertime',
            name='over_time_type',
            field=models.CharField(choices=[('REFRESH_OVER_TIME', 'Refresh chart and table, when user select new data.'), ('APPEND_OVER_TIME', 'Append to chart and table, when user select new data.')], default='REFRESH_OVER_TIME', max_length=17),
        ),
        migrations.AlterField(
            model_name='stateovertime',
            name='over_time_type',
            field=models.CharField(choices=[('REFRESH_OVER_TIME', 'Refresh chart and table, when user select new data.'), ('APPEND_OVER_TIME', 'Append to chart and table, when user select new data.')], default='REFRESH_OVER_TIME', max_length=17),
        ),
    ]
