# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_auto_20160826_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdisplaydatay',
            name='prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='districtdisplaydatay',
            name='suffix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schooldisplaydatay',
            name='prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schooldisplaydatay',
            name='suffix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='statedisplaydatay',
            name='prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='statedisplaydatay',
            name='suffix',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
