# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_auto_20160826_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdimensionxname',
            name='sorting_plug',
            field=models.CharField(blank=True, help_text='https://datatables.net/plug-ins/sorting/', max_length=100, null=True),
        ),
    ]
