# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_customdimensionxname_sorting_plug'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtindicatordataset',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolindicatordataset',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stateindicatordataset',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
