# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_auto_20160901_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictOverTimeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolOverTimeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StateOverTimeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='districtindicator',
            name='over_time',
        ),
        migrations.RemoveField(
            model_name='schoolindicator',
            name='over_time',
        ),
        migrations.RemoveField(
            model_name='stateindicator',
            name='over_time',
        ),
        migrations.AddField(
            model_name='districtovertime',
            name='district_overtime_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictOverTimeSet'),
        ),
        migrations.AddField(
            model_name='schoolovertime',
            name='school_overtime_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolOverTimeSet'),
        ),
        migrations.AddField(
            model_name='stateovertime',
            name='state_overtime_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateOverTimeSet'),
        ),
    ]
