# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_auto_20160901_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtindicator',
            name='over_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DistrictOverTimeSet'),
        ),
        migrations.AddField(
            model_name='schoolindicator',
            name='over_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolOverTimeSet'),
        ),
        migrations.AddField(
            model_name='stateindicator',
            name='over_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.StateOverTimeSet'),
        ),
    ]
