# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0060_auto_20160901_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtovertime',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schoolovertime',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stateovertime',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
