# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_auto_20160901_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
