# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_page.Category'),
        ),
    ]
