# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0005_about_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
