# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0006_auto_20161007_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
