# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0007_auto_20161007_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
