# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0008_about_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active page'),
        ),
    ]
