# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0009_about_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
