from django.core.management.base import BaseCommand, CommandError
from optparse import make_option
import sys

class Command(BaseCommand):

    help = ''

    def handle(self, *args, **options):
        import os
        from data.models import SchoolDisplayDataYDetail
        def create_detail_set(detail):
            from data.models import SchoolDisplayDataYDetailSet
            SchoolDisplayDataYDetailSet.objects.get_or_create(detail=detail, name="School vs Statewide", title="School vs Statewide", order=1)
            SchoolDisplayDataYDetailSet.objects.get_or_create(detail=detail, name="Ethnicity and Migrant Status", title="Ethnicity and Migrant Status", order=2)
            SchoolDisplayDataYDetailSet.objects.get_or_create(detail=detail, name="Poverty and Gender", title="Poverty and Gender", order=3)
            SchoolDisplayDataYDetailSet.objects.get_or_create(detail=detail, name="Disabilities and ELL", title="Disabilities and ELL", order=4)
            
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 1st Grade Math")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 2nd Grade Math")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 3th Grade Math")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 4th Grade Math")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 5th Grade Math")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 6th Grade Math")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 7th Grade Math")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 8th Grade Math")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 9th Grade Math")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 10th Grade Math")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 11th Grade Math")
        create_detail_set(detail)
        
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 1st Grade Reading")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 2nd Grade Reading")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 3th Grade Reading")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 4th Grade Reading")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 5th Grade Reading")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 6th Grade Reading")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 7th Grade Reading")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 8th Grade Reading")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 9th Grade Reading")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 10th Grade Reading")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 11th Grade Reading")
        create_detail_set(detail)
        
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 1st Grade Writing")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 2nd Grade Writing")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 3th Grade Writing")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 4th Grade Writing")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 5th Grade Writing")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 6th Grade Writing")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 7th Grade Writing")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 8th Grade Writing")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 9th Grade Writing")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 10th Grade Writing")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 11th Grade Writing")
        create_detail_set(detail)
        
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 1st Grade Science")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 2nd Grade Science")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 3th Grade Science")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 4th Grade Science")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 5th Grade Science")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 6th Grade Science")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 7th Grade Science")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 8th Grade Science")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 9th Grade Science")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 10th Grade Science")
        create_detail_set(detail)
        detail, created = SchoolDisplayDataYDetail.objects.get_or_create(name="School NECAP 11th Grade Science")
        create_detail_set(detail)
        
