# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('match_option', models.CharField(blank=True, choices=[('DISTRICT_CODE', 'district_code'), ('DISTRICT_NAME', 'district_name'), ('ADDRESS', 'address'), ('CITY', 'city'), ('STATE', 'state'), ('ZIP', 'zip'), ('PHONE', 'phone'), ('WEB_SITE', 'web_site'), ('SUPERINTENDENT', 'Superintendent')], help_text='(required) Select district_code, district_name, address, city, state, zip, phone, web_site, superintendent', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='District_Information')),
            ],
        ),
        migrations.AddField(
            model_name='districtfield',
            name='district_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.DistrictFile'),
        ),
    ]
