# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtfield',
            name='match_option',
            field=models.CharField(blank=True, choices=[('DISTRICT_CODE', 'district_code'), ('DISTRICT_NAME', 'district_name'), ('ADDRESS', 'address'), ('CITY', 'city'), ('STATE', 'state'), ('ZIP', 'zip'), ('PHONE', 'phone'), ('WEB_SITE', 'web_site'), ('SUPERINTENDENT', 'Superintendent'), ('DESCRIPTION', 'Description')], help_text='(required) Select district_code, district_name, address, city, state, zip, phone, web_site, superintendent', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='schoolfield',
            name='match_option',
            field=models.CharField(blank=True, choices=[('DISTRICT_CODE', 'district_code'), ('PRINCIPAL', 'principal'), ('SCHOOL_CODE', 'school_code'), ('SCHOOL_NAME', 'school_name'), ('SCHOOL_TYPE', 'school_type'), ('GRADE_TYPE', 'grade_type'), ('ADDRESS', 'address'), ('CITY', 'city'), ('STATE', 'state'), ('ZIP', 'zip'), ('PHONE', 'phone'), ('WEB_SITE', 'web_site'), ('LOW_GRADE', 'low_grade'), ('HIGH_GRADE', 'high_grade'), ('DESCRIPTION', 'Description')], help_text='(required) [low_grade and high_grade only accept PK, K, and 1 - 12] [grade_type only accept "Emh"]', max_length=30, null=True),
        ),
    ]
