# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0002_auto_20160219_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfield',
            name='school_file',
        ),
        migrations.DeleteModel(
            name='SchoolField',
        ),
    ]
