# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20160301_1413'),
        ('dataimport', '0003_auto_20160301_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('match_option', models.CharField(blank=True, choices=[('STATE_CODE', 'state_code'), ('STATE_NAME', 'state_name'), ('ADDRESS', 'address'), ('CITY', 'city'), ('STATE', 'state'), ('ZIP', 'zip'), ('PHONE', 'phone'), ('WEB_SITE', 'web_site'), ('COMMISSIONER', 'Commissioner'), ('DESCRIPTION', 'Description'), ('NUMBER_STUDENT', 'number of student'), ('NUMBER_TEACHER', 'number of teacher'), ('NUMBER_SCHOOL', 'number of school')], help_text='(required) Select state_code, state_name, address, city, state, zip, phone, web_site, commissioner', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='State_Information')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SchoolYear')),
            ],
        ),
        migrations.AddField(
            model_name='indicatorfile',
            name='state_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statefield',
            name='state_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.StateFile'),
        ),
    ]
