# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0004_auto_20160301_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtfield',
            name='match_option',
            field=models.CharField(blank=True, choices=[('STATE_CODE', 'state_code'), ('DISTRICT_CODE', 'district_code'), ('DISTRICT_NAME', 'district_name'), ('ADDRESS', 'address'), ('CITY', 'city'), ('STATE', 'state'), ('ZIP', 'zip'), ('PHONE', 'phone'), ('WEB_SITE', 'web_site'), ('SUPERINTENDENT', 'Superintendent'), ('DESCRIPTION', 'Description'), ('NUMBER_STUDENT', 'number of student'), ('NUMBER_TEACHER', 'number of teacher')], help_text='(required) Select district_code, district_name, address, city, state, zip, phone, web_site, superintendent', max_length=30, null=True),
        ),
    ]
