# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20160311_1516'),
        ('dataimport', '0006_auto_20160310_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorDetailField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('match_option', models.CharField(blank=True, choices=[('STATE_CODE', 'state_code (required pick one)'), ('DISTRICT_CODE', 'district_code (required pick one)'), ('SCHOOL_CODE', 'school_code (required pick one)'), ('DIMENSION', 'dimension')], help_text='(required)', max_length=30, null=True)),
                ('data_type', models.CharField(blank=True, choices=[('NUMERIC', 'numeric'), ('STRING', 'string')], help_text='(required)', max_length=30, null=True)),
                ('dimension_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName')),
            ],
        ),
        migrations.AddField(
            model_name='indicatordetailfile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Category'),
        ),
        migrations.AddField(
            model_name='indicatordetailfile',
            name='dimension_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionName'),
        ),
        migrations.AddField(
            model_name='indicatordetailfile',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.IndicatorTitle'),
        ),
        migrations.AddField(
            model_name='indicatordetailfile',
            name='indicator_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.DimensionFor'),
        ),
        migrations.AlterField(
            model_name='indicatordetailfile',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.SchoolYear'),
        ),
        migrations.AddField(
            model_name='indicatordetailfield',
            name='indicator_detail_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.IndicatorDetailFile'),
        ),
    ]
