# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0007_auto_20160314_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookUpTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LookUpTableElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(blank=True, max_length=100)),
                ('system_code', models.CharField(blank=True, max_length=100)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.LookUpTable')),
            ],
        ),
        migrations.AddField(
            model_name='indicatorfield',
            name='lookup_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataimport.LookUpTable'),
        ),
    ]
