# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0007_auto_20160311_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordetailfield',
            name='match_option',
            field=models.CharField(blank=True, choices=[('STATE_CODE', 'state_code (required pick one)'), ('DISTRICT_CODE', 'district_code (required pick one)'), ('SCHOOL_CODE', 'school_code (required pick one)'), ('INDICATOR_NAME', 'indicator name'), ('SCHOOL_YEAR', 'school year'), ('DIMENSION_NAME', 'dimension name'), ('DIMENSION', 'dimension (required)')], help_text='(required)', max_length=30, null=True),
        ),
    ]
