# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0008_auto_20160311_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordetailfile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.DetailDataSetTitle'),
        ),
    ]
