# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0006_auto_20160310_1811'),
        ('dataimport', '0009_auto_20160317_1542'),
    ]

    operations = [
    ]
