# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0010_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorfield',
            name='match_option',
            field=models.CharField(blank=True, choices=[('SCHOOL_YEAR', 'school_year'), ('STATE_CODE', 'state_code (required pick one)'), ('DISTRICT_CODE', 'district_code (required pick one)'), ('SCHOOL_CODE', 'school_code (required pick one)'), ('DIMENSION', 'dimension'), ('01_ADD_ON', '1. add on "[data]"'), ('02_ADD_ON_WITH_HEADER', '1. add on with header "[header] [data]"'), ('03_ADD_ON', '2. add on "[data]"'), ('04_ADD_ON_WITH_HEADER', '2. add on with header "[header] [data]"'), ('05_ADD_ON', '3. add on "[data]"'), ('06_ADD_ON_WITH_HEADER', '3. add on with header "[header] [data]"'), ('07_ADD_ON', '4. add on "[data]"'), ('08_ADD_ON_WITH_HEADER', '4. add on with header "[header] [data]"'), ('09_ADD_ON', '5. add on "[data]"'), ('10_ADD_ON_WITH_HEADER', '5. add on with header "[header] [data]"')], help_text='(required)', max_length=30, null=True),
        ),
    ]
