# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0013_auto_20160323_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookuptable',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
