# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0014_lookuptable_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcode',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
