# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0015_systemcode_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtfile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='schoolfile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='statefile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolfield',
            name='match_option',
            field=models.CharField(blank=True, choices=[('DISTRICT_CODE', 'district_code'), ('PRINCIPAL', 'principal'), ('SCHOOL_CODE', 'school_code (required)'), ('SCHOOL_NAME', 'school_name'), ('SHORT_NAME', 'short_name'), ('SCHOOL_TYPE', 'school_type'), ('GRADE_TYPE', 'grade_type'), ('ADDRESS', 'address'), ('CITY', 'city'), ('STATE', 'state'), ('ZIP', 'zip'), ('PHONE', 'phone'), ('WEB_SITE', 'web_site'), ('LOW_GRADE', 'low_grade'), ('HIGH_GRADE', 'high_grade'), ('DESCRIPTION', 'Description'), ('NUMBER_STUDENT', 'number of student'), ('NUMBER_TEACHER', 'number of teacher')], help_text='(required) [low_grade and high_grade only accept PK, K, and 1 - 12] [grade_type only accept "Emh"]', max_length=30, null=True),
        ),
    ]
